class CountriesDataMigration < ActiveRecord::Migration

  class Country < ActiveRecord::Base
  end

  def change
    create_table :countries do |t|
      t.string :name, :limit => 50
      t.string :code, :limit => 2
    end

    Country.reset_column_information
    Country.create(:code => 'AF', :name => 'AFGHANISTAN')
    Country.create(:code => 'AL', :name => 'ALBANIA')
    Country.create(:code => 'DZ', :name => 'ALGERIA')
    Country.create(:code => 'AS', :name => 'AMERICAN SAMOA')
    Country.create(:code => 'AD', :name => 'ANDORRA')
    Country.create(:code => 'AO', :name => 'ANGOLA')
    Country.create(:code => 'AI', :name => 'ANGUILLA')
    Country.create(:code => 'AG', :name => 'ANTIGUA AND BARBUDA')
    Country.create(:code => 'AR', :name => 'ARGENTINA')
    Country.create(:code => 'AM', :name => 'ARMENIA')
    Country.create(:code => 'AW', :name => 'ARUBA')
    Country.create(:code => 'AU', :name => 'AUSTRALIA')
    Country.create(:code => 'AT', :name => 'AUSTRIA')
    Country.create(:code => 'AZ', :name => 'AZERBAIJAN')
    Country.create(:code => 'BS', :name => 'BAHAMAS')
    Country.create(:code => 'BH', :name => 'BAHRAIN')
    Country.create(:code => 'BD', :name => 'BANGLADESH')
    Country.create(:code => 'BB', :name => 'BARBADOS')
    Country.create(:code => 'BY', :name => 'BELARUS')
    Country.create(:code => 'BE', :name => 'BELGIUM')
    Country.create(:code => 'BZ', :name => 'BELIZE')
    Country.create(:code => 'BJ', :name => 'BENIN')
    Country.create(:code => 'BM', :name => 'BERMUDA')
    Country.create(:code => 'BT', :name => 'BHUTAN')
    Country.create(:code => 'BO', :name => 'BOLIVIA')
    Country.create(:code => 'BA', :name => 'BOSNIA AND HERZEGOVINA')
    Country.create(:code => 'BW', :name => 'BOTSWANA')
    Country.create(:code => 'BR', :name => 'BRAZIL')
    Country.create(:code => 'BN', :name => 'BRUNEI DARUSSALAM')
    Country.create(:code => 'BG', :name => 'BULGARIA')
    Country.create(:code => 'BF', :name => 'BURKINA FASO')
    Country.create(:code => 'BI', :name => 'BURUNDI')
    Country.create(:code => 'KH', :name => 'CAMBODIA')
    Country.create(:code => 'CM', :name => 'CAMEROON')
    Country.create(:code => 'CA', :name => 'CANADA')
    Country.create(:code => 'CV', :name => 'CAPE VERDE')
    Country.create(:code => 'KY', :name => 'CAYMAN ISLANDS')
    Country.create(:code => 'CF', :name => 'CENTRAL AFRICAN REPUBLIC')
    Country.create(:code => 'TD', :name => 'CHAD')
    Country.create(:code => 'CL', :name => 'CHILE')
    Country.create(:code => 'CN', :name => 'CHINA')
    Country.create(:code => 'CO', :name => 'COLOMBIA')
    Country.create(:code => 'KM', :name => 'COMOROS')
    Country.create(:code => 'CG', :name => 'CONGO')
    Country.create(:code => 'CD', :name => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE')
    Country.create(:code => 'CK', :name => 'COOK ISLANDS')
    Country.create(:code => 'CR', :name => 'COSTA RICA')
    Country.create(:code => 'CI', :name => 'COTE D\'IVOIRE')
    Country.create(:code => 'HR', :name => 'CROATIA')
    Country.create(:code => 'CU', :name => 'CUBA')
    Country.create(:code => 'CY', :name => 'CYPRUS')
    Country.create(:code => 'CZ', :name => 'CZECH REPUBLIC')
    Country.create(:code => 'DK', :name => 'DENMARK')
    Country.create(:code => 'DJ', :name => 'DJIBOUTI')
    Country.create(:code => 'DM', :name => 'DOMINICA')
    Country.create(:code => 'DO', :name => 'DOMINICAN REPUBLIC')
    Country.create(:code => 'EC', :name => 'ECUADOR')
    Country.create(:code => 'EG', :name => 'EGYPT')
    Country.create(:code => 'SV', :name => 'EL SALVADOR')
    Country.create(:code => 'GQ', :name => 'EQUATORIAL GUINEA')
    Country.create(:code => 'ER', :name => 'ERITREA')
    Country.create(:code => 'EE', :name => 'ESTONIA')
    Country.create(:code => 'ET', :name => 'ETHIOPIA')
    Country.create(:code => 'FK', :name => 'FALKLAND ISLANDS (MALVINAS)')
    Country.create(:code => 'FO', :name => 'FAROE ISLANDS')
    Country.create(:code => 'FJ', :name => 'FIJI')
    Country.create(:code => 'FI', :name => 'FINLAND')
    Country.create(:code => 'FR', :name => 'FRANCE')
    Country.create(:code => 'GF', :name => 'FRENCH GUIANA')
    Country.create(:code => 'PF', :name => 'FRENCH POLYNESIA')
    Country.create(:code => 'GA', :name => 'GABON')
    Country.create(:code => 'GM', :name => 'GAMBIA')
    Country.create(:code => 'GE', :name => 'GEORGIA')
    Country.create(:code => 'DE', :name => 'GERMANY')
    Country.create(:code => 'GH', :name => 'GHANA')
    Country.create(:code => 'GI', :name => 'GIBRALTAR')
    Country.create(:code => 'GR', :name => 'GREECE')
    Country.create(:code => 'GL', :name => 'GREENLAND')
    Country.create(:code => 'GD', :name => 'GRENADA')
    Country.create(:code => 'GP', :name => 'GUADELOUPE')
    Country.create(:code => 'GU', :name => 'GUAM')
    Country.create(:code => 'GT', :name => 'GUATEMALA')
    Country.create(:code => 'GN', :name => 'GUINEA')
    Country.create(:code => 'GW', :name => 'GUINEA-BISSAU')
    Country.create(:code => 'GY', :name => 'GUYANA')
    Country.create(:code => 'HT', :name => 'HAITI')
    Country.create(:code => 'VA', :name => 'HOLY SEE (VATICAN CITY STATE)')
    Country.create(:code => 'HN', :name => 'HONDURAS')
    Country.create(:code => 'HK', :name => 'HONG KONG')
    Country.create(:code => 'HU', :name => 'HUNGARY')
    Country.create(:code => 'IS', :name => 'ICELAND')
    Country.create(:code => 'IN', :name => 'INDIA')
    Country.create(:code => 'ID', :name => 'INDONESIA')
    Country.create(:code => 'IR', :name => 'IRAN, ISLAMIC REPUBLIC OF')
    Country.create(:code => 'IQ', :name => 'IRAQ')
    Country.create(:code => 'IE', :name => 'IRELAND')
    Country.create(:code => 'IL', :name => 'ISRAEL')
    Country.create(:code => 'IT', :name => 'ITALY')
    Country.create(:code => 'JM', :name => 'JAMAICA')
    Country.create(:code => 'JP', :name => 'JAPAN')
    Country.create(:code => 'JO', :name => 'JORDAN')
    Country.create(:code => 'KZ', :name => 'KAZAKHSTAN')
    Country.create(:code => 'KE', :name => 'KENYA')
    Country.create(:code => 'KI', :name => 'KIRIBATI')
    Country.create(:code => 'KP', :name => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF')
    Country.create(:code => 'KR', :name => 'KOREA, REPUBLIC OF')
    Country.create(:code => 'KW', :name => 'KUWAIT')
    Country.create(:code => 'KG', :name => 'KYRGYZSTAN')
    Country.create(:code => 'LA', :name => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC')
    Country.create(:code => 'LV', :name => 'LATVIA')
    Country.create(:code => 'LB', :name => 'LEBANON')
    Country.create(:code => 'LS', :name => 'LESOTHO')
    Country.create(:code => 'LR', :name => 'LIBERIA')
    Country.create(:code => 'LY', :name => 'LIBYAN ARAB JAMAHIRIYA')
    Country.create(:code => 'LI', :name => 'LIECHTENSTEIN')
    Country.create(:code => 'LT', :name => 'LITHUANIA')
    Country.create(:code => 'LU', :name => 'LUXEMBOURG')
    Country.create(:code => 'MO', :name => 'MACAO')
    Country.create(:code => 'MK', :name => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF')
    Country.create(:code => 'MG', :name => 'MADAGASCAR')
    Country.create(:code => 'MW', :name => 'MALAWI')
    Country.create(:code => 'MY', :name => 'MALAYSIA')
    Country.create(:code => 'MV', :name => 'MALDIVES')
    Country.create(:code => 'ML', :name => 'MALI')
    Country.create(:code => 'MT', :name => 'MALTA')
    Country.create(:code => 'MH', :name => 'MARSHALL ISLANDS')
    Country.create(:code => 'MQ', :name => 'MARTINIQUE')
    Country.create(:code => 'MR', :name => 'MAURITANIA')
    Country.create(:code => 'MU', :name => 'MAURITIUS')
    Country.create(:code => 'MX', :name => 'MEXICO')
    Country.create(:code => 'FM', :name => 'MICRONESIA, FEDERATED STATES OF')
    Country.create(:code => 'MD', :name => 'MOLDOVA, REPUBLIC OF')
    Country.create(:code => 'MC', :name => 'MONACO')
    Country.create(:code => 'MN', :name => 'MONGOLIA')
    Country.create(:code => 'MS', :name => 'MONTSERRAT')
    Country.create(:code => 'MA', :name => 'MOROCCO')
    Country.create(:code => 'MZ', :name => 'MOZAMBIQUE')
    Country.create(:code => 'MM', :name => 'MYANMAR')
    Country.create(:code => 'NA', :name => 'NAMIBIA')
    Country.create(:code => 'NR', :name => 'NAURU')
    Country.create(:code => 'NP', :name => 'NEPAL')
    Country.create(:code => 'NL', :name => 'NETHERLANDS')
    Country.create(:code => 'AN', :name => 'NETHERLANDS ANTILLES')
    Country.create(:code => 'NC', :name => 'NEW CALEDONIA')
    Country.create(:code => 'NZ', :name => 'NEW ZEALAND')
    Country.create(:code => 'NI', :name => 'NICARAGUA')
    Country.create(:code => 'NE', :name => 'NIGER')
    Country.create(:code => 'NG', :name => 'NIGERIA')
    Country.create(:code => 'NU', :name => 'NIUE')
    Country.create(:code => 'NF', :name => 'NORFOLK ISLAND')
    Country.create(:code => 'MP', :name => 'NORTHERN MARIANA ISLANDS')
    Country.create(:code => 'NO', :name => 'NORWAY')
    Country.create(:code => 'OM', :name => 'OMAN')
    Country.create(:code => 'PK', :name => 'PAKISTAN')
    Country.create(:code => 'PW', :name => 'PALAU')
    Country.create(:code => 'PA', :name => 'PANAMA')
    Country.create(:code => 'PG', :name => 'PAPUA NEW GUINEA')
    Country.create(:code => 'PY', :name => 'PARAGUAY')
    Country.create(:code => 'PE', :name => 'PERU')
    Country.create(:code => 'PH', :name => 'PHILIPPINES')
    Country.create(:code => 'PN', :name => 'PITCAIRN')
    Country.create(:code => 'PL', :name => 'POLAND')
    Country.create(:code => 'PT', :name => 'PORTUGAL')
    Country.create(:code => 'PR', :name => 'PUERTO RICO')
    Country.create(:code => 'QA', :name => 'QATAR')
    Country.create(:code => 'RE', :name => 'REUNION')
    Country.create(:code => 'RO', :name => 'ROMANIA')
    Country.create(:code => 'RU', :name => 'RUSSIAN FEDERATION')
    Country.create(:code => 'RW', :name => 'RWANDA')
    Country.create(:code => 'SH', :name => 'SAINT HELENA')
    Country.create(:code => 'KN', :name => 'SAINT KITTS AND NEVIS')
    Country.create(:code => 'LC', :name => 'SAINT LUCIA')
    Country.create(:code => 'PM', :name => 'SAINT PIERRE AND MIQUELON')
    Country.create(:code => 'VC', :name => 'SAINT VINCENT AND THE GRENADINES')
    Country.create(:code => 'WS', :name => 'SAMOA')
    Country.create(:code => 'SM', :name => 'SAN MARINO')
    Country.create(:code => 'ST', :name => 'SAO TOME AND PRINCIPE')
    Country.create(:code => 'SA', :name => 'SAUDI ARABIA')
    Country.create(:code => 'SN', :name => 'SENEGAL')
    Country.create(:code => 'SC', :name => 'SEYCHELLES')
    Country.create(:code => 'SL', :name => 'SIERRA LEONE')
    Country.create(:code => 'SG', :name => 'SINGAPORE')
    Country.create(:code => 'SK', :name => 'SLOVAKIA')
    Country.create(:code => 'SI', :name => 'SLOVENIA')
    Country.create(:code => 'SB', :name => 'SOLOMON ISLANDS')
    Country.create(:code => 'SO', :name => 'SOMALIA')
    Country.create(:code => 'ZA', :name => 'SOUTH AFRICA')
    Country.create(:code => 'ES', :name => 'SPAIN')
    Country.create(:code => 'LK', :name => 'SRI LANKA')
    Country.create(:code => 'SD', :name => 'SUDAN')
    Country.create(:code => 'SR', :name => 'SURINAME')
    Country.create(:code => 'SJ', :name => 'SVALBARD AND JAN MAYEN')
    Country.create(:code => 'SZ', :name => 'SWAZILAND')
    Country.create(:code => 'SE', :name => 'SWEDEN')
    Country.create(:code => 'CH', :name => 'SWITZERLAND')
    Country.create(:code => 'SY', :name => 'SYRIAN ARAB REPUBLIC')
    Country.create(:code => 'TW', :name => 'TAIWAN, PROVINCE OF CHINA')
    Country.create(:code => 'TJ', :name => 'TAJIKISTAN')
    Country.create(:code => 'TZ', :name => 'TANZANIA, UNITED REPUBLIC OF')
    Country.create(:code => 'TH', :name => 'THAILAND')
    Country.create(:code => 'TG', :name => 'TOGO')
    Country.create(:code => 'TK', :name => 'TOKELAU')
    Country.create(:code => 'TO', :name => 'TONGA')
    Country.create(:code => 'TT', :name => 'TRINIDAD AND TOBAGO')
    Country.create(:code => 'TN', :name => 'TUNISIA')
    Country.create(:code => 'TR', :name => 'TURKEY')
    Country.create(:code => 'TM', :name => 'TURKMENISTAN')
    Country.create(:code => 'TC', :name => 'TURKS AND CAICOS ISLANDS')
    Country.create(:code => 'TV', :name => 'TUVALU')
    Country.create(:code => 'UG', :name => 'UGANDA')
    Country.create(:code => 'UA', :name => 'UKRAINE')
    Country.create(:code => 'AE', :name => 'UNITED ARAB EMIRATES')
    Country.create(:code => 'GB', :name => 'UNITED KINGDOM')
    Country.create(:code => 'US', :name => 'UNITED STATES')
    Country.create(:code => 'UY', :name => 'URUGUAY')
    Country.create(:code => 'UZ', :name => 'UZBEKISTAN')
    Country.create(:code => 'VU', :name => 'VANUATU')
    Country.create(:code => 'VE', :name => 'VENEZUELA')
    Country.create(:code => 'VN', :name => 'VIET NAM')
    Country.create(:code => 'VG', :name => 'VIRGIN ISLANDS, BRITISH')
    Country.create(:code => 'VI', :name => 'VIRGIN ISLANDS, U.S.')
    Country.create(:code => 'WF', :name => 'WALLIS AND FUTUNA')
    Country.create(:code => 'EH', :name => 'WESTERN SAHARA')
    Country.create(:code => 'YE', :name => 'YEMEN')
    Country.create(:code => 'ZM', :name => 'ZAMBIA')
    Country.create(:code => 'ZW', :name => 'ZIMBABWE')
  end
end
