eval(File.read(File.dirname(__FILE__) + '/../../magaz_shared_dependencies.rb'))

# Declare your gem's dependencies in magaz_core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec