source "https://rubygems.org"

# Use twitter bootstrap and font icons
gem 'anjlab-bootstrap-rails',
  require: 'bootstrap-rails',
  github: 'anjlab/bootstrap-rails'
gem 'font-awesome-sass-rails'

# Declare your gem's dependencies in magaz_style.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# Your gem is dependent on dev or edge Rails. Once you can lock this
# dependency down to a specific version, move it to your gemspec.
gem 'rails',            github: "rails/rails"
gem 'arel',             github: "rails/arel"

# Use edge version of sprockets-rails
gem 'sprockets-rails',  github: "rails/sprockets-rails"

# Use SCSS for stylesheets
gem 'sass-rails',       github: "rails/sass-rails"

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',             group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',           group: :development

# To use a debugger
# gem 'byebug', group: [:development, :test]
