source "https://rubygems.org"

# Declare your gem's dependencies in magaz_core.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.9', require: 'bcrypt'

# Use for upload files in app
gem "carrierwave"
gem "rmagick",          require: false

# Use liquid templates for themes
gem 'liquid'


# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# Your gem is dependent on dev or edge Rails. Once you can lock this
# dependency down to a specific version, move it to your gemspec.
gem 'rails',            github: 'rails/rails', branch: '4-2-stable'
# gem 'rack',             github: 'rack/rack'
# gem 'arel',             github: 'rails/arel'
# gem 'i18n',             github: 'svenfuchs/i18n'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',      group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',    group: :development

# To use a debugger
# gem 'byebug', group: [:development, :test]
gem 'annotate', github: 'ctran/annotate_models'